return {
  SINGULAR =
  {
    [WET_SUFFIX_KEY] = STRINGS.WET_SUFFIX.CLOTHING.FEMALE.SINGULAR, -- Empapada.

    "fishingnet", -- Tool object.
    "handpillow_beefalowool", -- Tool object.
    "handpillow_kelp", -- Tool object.
    "handpillow_petals", -- Tool object.
    "handpillow_steelwool", -- Tool object.
    "sleepbomb", -- Tool object.

    "alterguardianhat",
    "armor_bramble",
    "armor_lunarplant",
    "armor_sanity",
    "armor_voidcloth",
    "armordragonfly",
    "armordreadstone",
    "armorgrass",
    "armormarble",
    "armorruins",
    "armorskeleton",
    "armorsnurtleshell",
    "armorwood",
    "backpack",
    "bodypillow_beefalowool",
    "bodypillow_kelp",
    "bodypillow_petals",
    "bodypillow_steelwool",
    "candybag",
    "carnival_vest_a",
    "carnival_vest_b",
    "carnival_vest_c",
    "catcoonhat",
    "cavein_boulder",
    "chesspiece_anchor",
    "chesspiece_antlion",
    "chesspiece_bearger",
    "chesspiece_beefalo",
    "chesspiece_beequeen",
    "chesspiece_bishop",
    "chesspiece_butterfly",
    "chesspiece_carrat",
    "chesspiece_catcoon",
    "chesspiece_clayhound",
    "chesspiece_claywarg",
    "chesspiece_crabking",
    "chesspiece_daywalker",
    "chesspiece_deerclops",
    "chesspiece_dragonfly",
    "chesspiece_eyeofterror",
    "chesspiece_formal",
    "chesspiece_guardianphase3",
    "chesspiece_kitcoon",
    "chesspiece_klaus",
    "chesspiece_knight",
    "chesspiece_malbatross",
    "chesspiece_manrabbit",
    "chesspiece_minotaur",
    "chesspiece_moon",
    "chesspiece_moosegoose",
    "chesspiece_muse",
    "chesspiece_pawn",
    "chesspiece_pipe",
    "chesspiece_rook",
    "chesspiece_stalker",
    "chesspiece_toadstool",
    "chesspiece_twinsofterror",
    "dragonfruit_oversized",
    "dragonfruit_oversized_rotten",
    "dragonfruit_oversized_waxed",
    "dragonheadhat",
    "dragontailhat",
    "eggplant_oversized",
    "eggplant_oversized_rotten",
    "eggplant_oversized_waxed",
    "eyebrellahat",
    "eyemaskhat",
    "flowerhat",
    "hawaiianshirt",
    "hivehat",
    "icepack",
    "kelphat",
    "krampus_sack",
    "mask_blacksmithhat",
    "mask_dollbrokenhat",
    "mask_dollhat",
    "mask_dollrepairedhat",
    "mask_foolhat",
    "mask_kinghat",
    "mask_mirrorhat",
    "mask_queenhat",
    "mask_treehat",
    "monkey_smallhat",
    "moon_altar_glass",
    "moon_altar_ward",
    "oceantreenut",
    "onemanband",
    "onion_oversized",
    "onion_oversized_rotten",
    "onion_oversized_waxed",
    "piggyback",
    "pomegranate_oversized",
    "pomegranate_oversized_rotten",
    "pomegranate_oversized_waxed",
    "potato_oversized",
    "potato_oversized_rotten",
    "potato_oversized_waxed",
    "pumpkin_oversized",
    "pumpkin_oversized_rotten",
    "pumpkin_oversized_waxed",
    "ruinshat",
    "spicepack",
    "voidclothhat",
    "walrushat",
    "watermelon_oversized",
    "watermelon_oversized_rotten",
    "watermelon_oversized_waxed",
    "yellowamulet"
  },

  PLURAL =
  {
    [WET_SUFFIX_KEY] = STRINGS.WET_SUFFIX.CLOTHING.FEMALE.PLURAL, -- Empapadas.

    "carrot_oversized",
    "carrot_oversized_rotten",
    "carrot_oversized_waxed",
    "deserthat",
    "earmuffshat",
    "goggleshat",
    "molehat",
    "moonstorm_goggleshat"
  }
}
