return {
  SINGULAR =
  {
    SUFFIX = STRINGS.WET_SUFFIX.FUEL.FEMALE.SINGULAR, -- Mojada.

    "bathbomb",
    "beefalowool",
    "blackflag",
    "carnivaldecor_figure_kit",
    "carnivaldecor_figure_kit_season2",
    "compost",
    "compostwrap",
    "dug_grass",
    "feather_canary",
    "feather_crow",
    "feather_robin",
    "feather_robin_winter",
    "fence_gate_item",
    "fence_item",
    "ghostlyelixir_attack",
    "ghostlyelixir_retaliation",
    "ghostlyelixir_shield",
    "ghostlyelixir_slowregen",
    "halloween_ornament_1",
    "halloween_ornament_2",
    "halloween_ornament_3",
    "halloween_ornament_4",
    "halloween_ornament_5",
    "halloween_ornament_6",
    "halloweenpotion_moon",
    "livingtree_root",
    "malbatross_feather",
    "malbatross_feathered_weave",
    "miniboatlantern",
    "minisign_drawn",
    "minisign_item",
    "palmcone_scale",
    "pinecone",
    "playbill_the_doll",
    "pocket_scale",
    "rope",
    "scrapbook_page",
    "slurtleslime",
    "steelwool",
    "turf_archive",
    "turf_beard_rug",
    "turf_carpetfloor2",
    "turf_ruinstrim",
    "winter_ornament_light1",
    "winter_ornament_light2",
    "winter_ornament_light3",
    "winter_ornament_light4",
    "winter_ornament_light5",
    "winter_ornament_light6",
    "winter_ornament_light7",
    "winter_ornament_light8",
    "yotb_beefalo_doll_beast",
    "yotb_beefalo_doll_doll",
    "yotb_beefalo_doll_festive",
    "yotb_beefalo_doll_formal",
    "yotb_beefalo_doll_ice",
    "yotb_beefalo_doll_nature",
    "yotb_beefalo_doll_robot",
    "yotb_beefalo_doll_victorian",
    "yotr_decor_1_item",
    "yotr_decor_2_item"
  },

  PLURAL =
  {
    SUFFIX = STRINGS.WET_SUFFIX.FUEL.FEMALE.PLURAL, -- Mojadas.

    "dug_monkeytail",
    "fireflies",
    "glommerwings",
    "monkeytail"
  }
}
